# Generated by Django 3.0.4 on 2020-03-24 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.App')),
            ],
        ),
    ]
