# Generated by Django 3.0.4 on 2020-03-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20200324_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='changelog',
            field=models.CharField(max_length=512),
        ),
    ]
