# Generated by Django 3.0.4 on 2020-03-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20200324_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='app',
            name='solid',
            field=models.BooleanField(default=True),
        ),
    ]
