# Generated by Django 3.0.4 on 2020-03-25 16:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20200325_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
