# Generated by Django 3.1 on 2020-11-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_auto_20200820_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='semantic_version',
            field=models.CharField(choices=[('Maj', 'Major'), ('Min', 'Minor'), ('Pat', 'Patch')], default='Pat', max_length=3),
        ),
    ]
