# Generated by Django 3.2.5 on 2021-07-19 10:54

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_version_semantic_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.IntegerField()),
                ('date', month.models.MonthField(verbose_name='date')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.app')),
            ],
        ),
    ]
