# Generated by Django 3.0.4 on 2020-05-05 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='size',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Content'),
        ),
    ]
